// SPDX-License-Identifier: Apache-2.0
//
// farsee test harness: runner + assertion helpers.
//
// Design (plan.md §5.5): test files are #include'd into this single
// translation unit via the generated test_includes.generated.h, so the
// whole suite compiles to one object with no constructors (which
// deadlock under ASan on macOS) and no linker sections (which modern
// Apple ld does not emit reliably). The registry array is generated by
// tools/gen_test_registry.py.
//
// The Makefile regenerates both artifacts whenever the set of test
// files changes.

#include "rfb_test.h"

// Pull every test source into this TU, and the generated registry.
#include "test_includes.generated.h"
#include "registry.generated.c"

#include <stdarg.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

// Per-test mutable state (the only globals; touched only between tests).
bool        rfb_test__current_failed = false;
bool        rfb_test__current_skipped = false;
const char *rfb_test__current_name = "";
size_t      rfb_test__current_assert_line = 0;
const char *rfb_test__current_assert_file = "";

// --- Failure formatting state ----------------------------------------------
static char   g_last_msg[512];
static char   g_last_file[256];
static size_t g_last_line;

void rfb_test__record_failure(const char *file, size_t line, const char *msg)
{
    if (g_last_msg[0] == '\0') {
        snprintf(g_last_msg, sizeof g_last_msg, "%s", msg ? msg : "(no msg)");
    }
    snprintf(g_last_file, sizeof g_last_file, "%s", file ? file : "?");
    g_last_line = line;
}

void rfb_test__fail_fmt(const char *file, size_t line, const char *fmt, ...)
{
    char buf[512];
    va_list ap;
    va_start(ap, fmt);
    // fmt is always a literal from our own macros; suppress the
    // -Wformat-nonliteral warning locally without weakening the
    // project-wide -Wformat-security policy.
#if defined(__clang__)
#  pragma clang diagnostic push
#  pragma clang diagnostic ignored "-Wformat-nonliteral"
#endif
    vsnprintf(buf, sizeof buf, fmt, ap);
#if defined(__clang__)
#  pragma clang diagnostic pop
#endif
    va_end(ap);
    rfb_test__fail_at(file, line, buf);
}

bool rfb_test_mem_eq_hex(
    const void *actual, const void *expected, size_t n)
{
    const unsigned char *a = (const unsigned char *)actual;
    const unsigned char *e = (const unsigned char *)expected;
    for (size_t i = 0; i < n; i++) {
        if (a[i] != e[i]) {
            return false;
        }
    }
    return true;
}

// --- Sorting for stable, grouped output -----------------------------------
static int cmp_entry(const rfb_test_entry *a, const rfb_test_entry *b)
{
    int c = strcmp(a->suite, b->suite);
    if (c != 0) return c;
    return strcmp(a->name, b->name);
}

static void reset_test_state(void)
{
    g_last_msg[0] = '\0';
    g_last_file[0] = '\0';
    g_last_line = 0;
    rfb_test__current_failed = false;
    rfb_test__current_skipped = false;
}

int main(int argc, char **argv)
{
    const char *filter = NULL;
    for (int i = 1; i < argc; i++) {
        if (strcmp(argv[i], "--filter") == 0 && i + 1 < argc) {
            filter = argv[++i];
        } else if (strncmp(argv[i], "--filter=", 9) == 0) {
            filter = argv[i] + 9;
        } else if (strcmp(argv[i], "--list") == 0) {
            for (size_t k = 0; k < rfb_test__all_entries_count; k++) {
                printf("%s::%s\n",
                       rfb_test__all_entries[k]->suite,
                       rfb_test__all_entries[k]->name);
            }
            return 0;
        } else {
            fprintf(stderr, "farsee_tests: unknown arg '%s'\n", argv[i]);
            fprintf(stderr, "usage: %s [--filter SUBSTR] [--list]\n",
                    argv[0]);
            return 2;
        }
    }

    // Sort a shallow copy of the registry for stable, grouped output.
    // The generated array is already sorted, but we re-sort defensively
    // in case the generation order ever changes. We never mutate the
    // records, only reorder pointers to them.
    const rfb_test_entry **sorted = NULL;
    if (rfb_test__all_entries_count > 0) {
        sorted = (const rfb_test_entry **)calloc(
            rfb_test__all_entries_count, sizeof(const rfb_test_entry *));
        if (sorted == NULL) {
            fprintf(stderr, "farsee_tests: out of memory\n");
            return 2;
        }
        for (size_t k = 0; k < rfb_test__all_entries_count; k++) {
            sorted[k] = rfb_test__all_entries[k];
        }
        for (size_t k = 1; k < rfb_test__all_entries_count; k++) {
            const rfb_test_entry *key = sorted[k];
            size_t j = k;
            while (j > 0 && cmp_entry(sorted[j - 1], key) > 0) {
                sorted[j] = sorted[j - 1];
                j--;
            }
            sorted[j] = key;
        }
    }

    size_t total = rfb_test__all_entries_count;
    size_t ran = 0;
    size_t passed = 0;
    size_t failed = 0;
    size_t skipped = 0;

    char last_suite[128] = "";
    size_t suite_passed = 0;
    size_t suite_failed = 0;

    for (size_t idx = 0; idx < total; idx++) {
        const rfb_test_entry *t = sorted[idx];
        if (filter != NULL && strstr(t->name, filter) == NULL) {
            skipped++;
            continue;
        }
        if (strcmp(t->suite, last_suite) != 0) {
            if (last_suite[0] != '\0') {
                printf("  [%s] %zu passed, %zu failed\n",
                       last_suite, suite_passed, suite_failed);
            }
            snprintf(last_suite, sizeof last_suite, "%s", t->suite);
            suite_passed = 0;
            suite_failed = 0;
            printf("\n== %s ==\n", t->suite);
        }

        ran++;
        reset_test_state();
        rfb_test__current_name = t->name;
        t->fn();
        if (rfb_test__current_skipped) {
            // A self-skipped test: count as skipped (not ran/passed/failed).
            ran--;
            skipped++;
            printf("  SKIP  %s\n", t->name);
        } else if (rfb_test__current_failed) {
            failed++;
            suite_failed++;
            printf("  FAIL  %s\n", t->name);
            if (g_last_file[0]) {
                printf("        %s:%zu: %s\n",
                       g_last_file, g_last_line, g_last_msg);
            }
        } else {
            passed++;
            suite_passed++;
            printf("  ok    %s\n", t->name);
        }
    }
    if (last_suite[0] != '\0') {
        printf("  [%s] %zu passed, %zu failed\n",
               last_suite, suite_passed, suite_failed);
    }

    printf("\n----------------------------------------"
           "----------------------------------------\n");
    printf("TESTS  total=%zu  ran=%zu  passed=%zu  failed=%zu  skipped=%zu\n",
           total, ran, passed, failed, skipped);
    printf("----------------------------------------"
           "----------------------------------------\n");
    free(sorted);
    return failed == 0 ? 0 : 1;
}
