#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Generate deterministic C constants from a validated semantic version."""

from __future__ import annotations

import argparse
import os
from pathlib import Path
import re


SEMVER = re.compile(
    r"^(0|[1-9][0-9]*)\."
    r"(0|[1-9][0-9]*)\."
    r"(0|[1-9][0-9]*)"
    r"(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?"
    r"(?:\+([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?$"
)
INT_MAX = 2_147_483_647


def parse_version(version: str) -> tuple[int, int, int, str]:
    match = SEMVER.fullmatch(version)
    if match is None:
        raise ValueError(f"invalid semantic version: {version!r}")
    major, minor, patch = (int(match.group(index)) for index in range(1, 4))
    if any(value > INT_MAX for value in (major, minor, patch)):
        raise ValueError("semantic version component exceeds C int range")
    prerelease = match.group(4)
    if prerelease is not None:
        for identifier in prerelease.split("."):
            if identifier.isdigit() and len(identifier) > 1 and identifier[0] == "0":
                raise ValueError(
                    "numeric prerelease identifiers must not have leading zeroes"
                )
    core = f"{major}.{minor}.{patch}"
    return major, minor, patch, version[len(core):]


def render(version: str) -> str:
    major, minor, patch, suffix = parse_version(version)
    return f"""// SPDX-License-Identifier: Apache-2.0
// Generated by tools/gen_version_header.py. Do not edit.

#ifndef FARSEE_BUILD_VERSION_H
#define FARSEE_BUILD_VERSION_H

#define FARSEE_VERSION_MAJOR {major}
#define FARSEE_VERSION_MINOR {minor}
#define FARSEE_VERSION_PATCH {patch}
#define FARSEE_VERSION_SUFFIX \"{suffix}\"
#define FARSEE_VERSION_STRING \"{version}\"

#endif  // FARSEE_BUILD_VERSION_H
"""


def write_if_changed(path: Path, content: str) -> None:
    try:
        if path.read_text(encoding="utf-8") == content:
            return
    except FileNotFoundError:
        pass
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("output", type=Path)
    parser.add_argument("--version")
    args = parser.parse_args()
    version = args.version or os.environ.get("FARSEE_GUARD_VERSION")
    if version is None:
        parser.error("--version or FARSEE_GUARD_VERSION is required")
    try:
        content = render(version)
    except ValueError as exc:
        parser.error(str(exc))
    write_if_changed(args.output, content)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
