#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Generate the farsee test registry.

Scans test source files for `RFB_TEST(suite, name) { ... }` invocations
and emits two artifacts consumed by the test runner:

  1. <out>/test_includes.generated.h
       A compatibility header containing no test-source includes. Test files
       compile independently.

  2. <out>/registry.generated.c
       Declares `extern const rfb_test_entry rfb_test_rec__<name>;` for
       every test, and defines `rfb_test__all_entries[]` (array of
       pointers) and `rfb_test__all_entries_count`. The array is sorted
       by (suite, name) at generation time so runner output is stable.

Usage:
    tools/gen_test_registry.py <test-root> <out-dir>

Test files must live under <test-root>/ and end with `.c`. The scanner
finds every `RFB_TEST( <suite>, <name> )` on a single line (the macro is
always invoked at column 0 per the plan.md §13.4 convention).
"""
from __future__ import annotations

import os
import re
import sys
from pathlib import Path

# Match: RFB_TEST(suite_name, test_name)
# - suite_name and test_name are C identifiers (the macro is always
#   invoked with bare identifiers, never string literals or expressions,
#   per the convention in rfb_test.h).
RFB_TEST_RE = re.compile(
    r"^\s*RFB_TEST\s*\(\s*([A-Za-z_][A-Za-z0-9_]*)\s*,\s*([A-Za-z_][A-Za-z0-9_]*)\s*\)",
    re.MULTILINE,
)


def scan_file(path: Path):
    text = path.read_text(encoding="utf-8", errors="replace")
    out = []
    for m in RFB_TEST_RE.finditer(text):
        suite = m.group(1)
        name = m.group(2)
        out.append((suite, name))
    return out


def main(argv):
    if len(argv) != 3:
        print("usage: gen_test_registry.py <test-root> <out-dir>",
              file=sys.stderr)
        return 2
    test_root = Path(argv[1]).resolve()
    out_dir = Path(argv[2]).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)
    if not test_root.is_dir():
        print(f"not a directory: {test_root}", file=sys.stderr)
        return 2

    # Collect test files. We look in unit/, component/, integration/
    # (those that compile into the runner; pure-script integration tests
    # under tests/integration/*.py are excluded by the .c filter).
    # Feature-gated subdirs under unit/: scanned ONLY when their feature env
    # var is "1", and EXCLUDED from the default unit/ scan so a no-feature
    # build's registry has no references to feature-only test symbols.
    feature_dirs = {
        "rdp": "FARSEE_WITH_RDP",
    }
    enabled_feature_dirs = {
        subdir for subdir, envvar in feature_dirs.items()
        if os.environ.get(envvar, "0") == "1"
    }
    test_files = []
    for sub in ("unit", "component"):
        d = test_root / sub
        if d.is_dir():
            for p in sorted(d.rglob("*.c")):
                # Skip feature-gated subdirs unless their feature is enabled.
                if sub == "unit":
                    rel = p.relative_to(d)
                    first_part = rel.parts[0] if rel.parts else ""
                    if first_part in feature_dirs and first_part not in enabled_feature_dirs:
                        continue
                test_files.append(p)
    # Also allow tests/*.c directly (rare).
    for p in sorted(test_root.glob("*.c")):
        test_files.append(p)

    # Scan every file; collect (file, suite, name).
    entries = []
    for tf in test_files:
        for suite, name in scan_file(tf):
            entries.append((tf, suite, name))

    # Sort by (suite, name) for deterministic output.
    entries.sort(key=lambda e: (e[1], e[2]))

    # Emit an intentionally empty compatibility header. Each test file
    # compiles independently; including .c files here would violate that
    # boundary.
    inc_path = out_dir / "test_includes.generated.h"
    with inc_path.open("w", encoding="utf-8") as f:
        f.write("// SPDX-License-Identifier: Apache-2.0\n")
        f.write("// AUTO-GENERATED by tools/gen_test_registry.py.\n")
        f.write("// Do not edit; regenerate via `make build`.\n")
        f.write("//\n")
        f.write("// Test sources compile independently; keep this header empty.\n")
        f.write("#pragma once\n")

    # Emit registry.
    reg_path = out_dir / "registry.generated.c"
    with reg_path.open("w", encoding="utf-8") as f:
        f.write("// SPDX-License-Identifier: Apache-2.0\n")
        f.write("// AUTO-GENERATED by tools/gen_test_registry.py.\n")
        f.write("// Do not edit; regenerate via `make build`.\n")
        f.write("//\n")
        f.write("// Declares every test record and defines the registry array.\n")
        f.write('#include "rfb_test.h"\n\n')
        for tf, suite, name in entries:
            rel = tf.relative_to(test_root.parent).as_posix()
            f.write(
                f"extern const rfb_test_entry rfb_test_rec__{name}; "
                f"// {rel}\n"
            )
        f.write("\n")
        f.write("const rfb_test_entry *const rfb_test__all_entries[] = {\n")
        for tf, suite, name in entries:
            f.write(f"    &rfb_test_rec__{name},\n")
        f.write("};\n\n")
        f.write("const size_t rfb_test__all_entries_count = "
                f"sizeof(rfb_test__all_entries) / "
                f"sizeof(rfb_test__all_entries[0]);\n")

    print(f"gen_test_registry: {len(entries)} tests across "
          f"{len(test_files)} files -> {reg_path.name} + {inc_path.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
