#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Write a stable, validated C build-identity header."""

from __future__ import annotations

import argparse
import os
import re
from pathlib import Path


REV_RE = re.compile(r"[A-Za-z0-9][A-Za-z0-9._+-]{0,63}\Z")
EPOCH_RE = re.compile(r"(?:0|[1-9][0-9]{0,19})\Z")


def main(argv=None):
    parser = argparse.ArgumentParser()
    parser.add_argument("output", type=Path)
    parser.add_argument("--rev")
    parser.add_argument("--epoch")
    args = parser.parse_args(argv)
    revision = args.rev or os.environ.get("FARSEE_AUDIT_SOURCE_REV")
    epoch = args.epoch or os.environ.get("FARSEE_AUDIT_SOURCE_DATE_EPOCH")
    if revision is None or REV_RE.fullmatch(revision) is None:
        parser.error("--rev must be 1..64 portable identity characters")
    if epoch is None or EPOCH_RE.fullmatch(epoch) is None:
        parser.error("--epoch must be an unsigned decimal integer")
    text = "\n".join(
        [
            "/* AUTO-GENERATED by tools/gen_build_id.py; do not edit. */",
            "#ifndef FARSEE_BUILD_ID_H",
            "#define FARSEE_BUILD_ID_H",
            f'#define FARSEE_GIT_REV "{revision}"',
            f'#define FARSEE_BUILD_TIME "source-date-epoch:{epoch}"',
            "#endif",
            "",
        ]
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    try:
        if args.output.read_text(encoding="utf-8") == text:
            return 0
    except FileNotFoundError:
        pass
    args.output.write_text(text, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
